### ISSUE TITLE
HOW-TO

### ISSUE THREAD

**Issue by ButtFace1212** [HeroCreationLab/hero-creation-tool#111]
The HOW-TO.md is no longer available. I'm adding custom races but without the HOW-TO.md I don't know what requirements need to be on a feature in order for it to be a race, subrace, racial feature, class, etc.
![image](https://user-images.githubusercontent.com/55815285/179373033-09e63619-13a4-4045-80c0-983bfd1b66e5.png)

**Comment by ccjmk** [comment]
Hi! Sorry, this was a big miss, I should have replaced the content with a proper link, but the stuff is now on the repository's wiki!

https://github.com/HeroCreationLab/hero-creation-tool/wiki/Custom-Content

**Comment by ccjmk** [comment]
@ButtFace1212 unless you have any other question about this, I will close this ticket now. Feel free to reply for reopen.
