### ISSUE TITLE
DDB imported races now showing correctly

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#113]
**Submitted By**: kililae@gmail.com
**Feedback Type**: Bug
 
**Core:** 9.269
**System:** dnd5e v1.6.1
**Module Version:** hero-creation-tool v1.8.2
 
**Description**:
I have imported races using the latest DDB importer and selected the compendium in the settings for the Hero Creation Tool but when I go to create a hero I only see a limited list of races. 

The races I see are: Aarakocra, Dragonborn, Goliath, Half-Elf, Half-Ord, Tiefling and Variant Human.

How do I get all the races to show? When I look in the list for the DDB Races I see all of the option but they're not showing in the hero creation tool.

Please help,
Kililae<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

about-time--v1.0.6;
ActiveAuras--v0.4.13;
advanced-macros--vv1.15;
ATL--v0.4.01;
autoanimations--v3.2.95;
blood-n-guts--v0.8.7;
bug-reporter--v1.3.3;
character-actions-list-5e--v5.0.2;
combat-carousel--v0.2.5;
dae--v0.10.25;
ddb-importer--v2.9.58;
dfreds-convenient-effects--v2.7.2;
dice-calculator--v1.5.2;
dice-so-nice--v4.5.1;
drag-ruler--v1.12.8;
elevation-drag-ruler--v1.6.3;
fa_battlemaps_free--v1.0.0;
foundryvtt-simple-calendar--v2.0.30;
hero-creation-tool--v1.8.2;
itemacro--v1.6.0;
JB2A_DnD5e--v0.4.5.01;
lib-wrapper--v1.12.7.0;
link-item-resource-5e--v1.2.1;
lootsheetnpc5e--v3.6.1;
magicitems--v2.2.1;
metric-system-dnd5e--v2.0.1;
midi-qol--v0.9.68;
monks-active-tiles--v1.0.90;
NotYourTurn--v1.2.7;
scaleGrid--v1.3.1;
scene-packer--v2.5.7;
searchanywhere--v2.3.4;
sequencer--v2.1.8;
socketlib--v1.0.10;
tagger--v1.3.5;
tidy5e-sheet--v0.5.33;
times-up--v0.8.32;
token-action-hud--v2.2.27;
tokenmagic--v0.5.4;
turnmarker--v2.9.0;
vtta-tokenizer--v3.9.2;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by ccjmk** [comment]
Hi Kililae! Just in case, are you sure you are using the correct compendiums on both cases (maybe you have different compendiums for the muncher and the HCT is using some other compendium you had with races from a previous version or something)

I just tried it myself and it seems to work as expected. I would also recommend trying with no other modules active other than DDBImporter and Hero Creation Tool, but given the nature of your issue, I don't expect any other module to be causing issue.

Another thing I'm thinking could be an issue is if you had munched your races/features a long time ago, there was some fixes made by MrPrimate to make the races the muncher created compatible with this module (the requirements were a little off)

![image](https://user-images.githubusercontent.com/4467128/181285704-cf9a7e0f-ce17-496a-ad55-4b4260693b72.png)

**Comment by ccjmk** [comment]
Given the lack of follow up, and that I can't seem to reproduce this, I will close this issue. Please feel free to reply back to reopen it if you still have problems in the future!
