### ISSUE TITLE
Bug Report : Subclass Name

### ISSUE THREAD

**Issue by RonaldoBrum** [HeroCreationLab/hero-creation-tool#114]
I'm having a problem: Subclass name doesn't appear

![image](https://user-images.githubusercontent.com/60355256/187045908-374f712b-875b-4d7c-88c8-d9737d6a5396.png)
![image](https://user-images.githubusercontent.com/60355256/187045914-1bf9fb8b-c63d-4bcb-ba97-77b4d9969528.png)

and it is not appearing in the "spells" option, a button to show the "item" conjuration on the right side tab, as in the previous tabs they have this option I believe to be a bug.

![image](https://user-images.githubusercontent.com/60355256/187045926-11f4cfe4-92be-407d-b811-1d71231b8cb0.png)

I've already activated the hero tool alone, with all modules deactivated, which confirmed me to be a bug and not a compatibility error.
Thanks for your attention, the tool is amazing.

**Comment by ccjmk** [comment]
oops! can you put me here the version of the 5e system and module you are using ?

**Comment by RonaldoBrum** [comment]
Foundry: V9 comp 245
dnd 5e: 1.6.3
Module Hero: 1.8.2

**Comment by ccjmk** [comment]
Oh,  definitely a bug, thanks! I broke something trying to make the module a little more good-looking when interacting with DDBImporter classes, I even missed adding an i18n translation value!

If you disable this module setting it should be back to how it looked before, I will try to fix this tomorrow or beginning of next week in a more permanent fashion.

![image](https://user-images.githubusercontent.com/4467128/187053408-cb5dc680-6b87-4ee8-80c6-2b899e66589e.png)
