### ISSUE TITLE
Use Requirements section to determine subraces instead of feature name

### ISSUE THREAD

**Issue by Dialectikal** [HeroCreationLab/hero-creation-tool#120]
Currently, subraces are matched by the race name being included in the subrace name.
Can this be changed to use the Requirements of the subrace feature?

**Comment by ccjmk** [comment]
Hi! unfortunately, this is currently not possible as there will be no way of telling apart a subrace from a racial feature; for example: High Elf and Fey Ancestry have the same requirement (and both are `Feature`-type items, and both are on the same compendium by default) _- as a little nitpic, it ALSO uses the requirement! to be recognized as a subrace, it has to have the parent race name AND requirement -_

This will be rendered a non-issue once `Race` and `Subrace`-type items are introduced by the system, but for the time being unfortunately it's either this or blacklisting/whitelisting feature or subclass names individually.

**Comment by Dialectikal** [comment]
I'm not sure if there are any other conflicts, but I was able to make this work by just moving all of the subraces into the Races compendium. I've made a few modifications locally to allow searching for races based on the requirements section.

![image](https://user-images.githubusercontent.com/31572084/190926594-6d0e49cd-1834-455f-bf0e-fed09dbe7823.png)

**Comment by Dialectikal** [comment]
It is unfortunate that they list the subraces in the Racial Features compendium. Maybe there is a workaround or a simple way to convey instructions to make it work. Idk
