### ISSUE TITLE
No pack for name [null]!

### ISSUE THREAD

**Issue by r04dw4rri0r** [HeroCreationLab/hero-creation-tool#121]
![990c270fa52bfc52aa9155b5aa25ec0d](https://user-images.githubusercontent.com/30304129/190916814-cc388457-c878-4dcd-bd1f-9bb35c36a57e.png)

**Comment by ccjmk** [comment]
That  is unusual; that error was more of a fail-safe than something I expected someone to see heheh

Could you run this on the console to see what your compendium sources module setting looks like?

>game.settings.get("hero-creation-tool", 'compendiumSources')

![image](https://user-images.githubusercontent.com/4467128/191792471-de3a951d-dab1-4d23-903c-ab77e0fdd16a.png)

**Comment by r04dw4rri0r** [comment]
[image: image.png]

**Comment by ccjmk** [comment]
Sorry, I can't see your image, it just shows [image: image.png]. Can you see it here in Github?

**Comment by r04dw4rri0r** [comment]
My apologies.
![image](https://user-images.githubusercontent.com/30304129/192031511-7831fbdf-969c-48fd-a44f-9926478919e7.png)

**Comment by ccjmk** [comment]
That is even weirder! can we see this live in discord ? PM me at ccjmk#0141 so we can arrange something

**Comment by ccjmk** [comment]
If you are running v10 now, you can try version 1.9.0, where there's also a new call to reset the sources to default:

```await game.modules.get("hero-creation-tool").api.resetSources()```

You can give that a try!

**Comment by r04dw4rri0r** [comment]
Updated the module and it seems to be working fine now!

**Comment by Wakarusa67** [comment]
I have the same issue as above No pack for name [null]!

**Comment by hedgehog8711** [comment]
I have noticed in my foundry system that it looks like its having issues when not using the standard compendiums. In my case I use the DDB importer and it seems that its having an issue not being able to read those compendiums, however if I just use the standard core ones then the tool works. 
![Capture](https://user-images.githubusercontent.com/114251484/193291609-546c9f30-1fe2-4a6c-91e4-eab66d2c5c35.PNG)

**Comment by ccjmk** [comment]
@hedgehog8711 this looks like another issue, could you open a separate ticket with this, and anything suspicious you see in the console (f12 on chrome, Ctrl + Shift + J on firefox)?

Also, please add to that ticket your foundry version, dnd5e version, module version (and please try this again with just the Hero Creation Tool enabled)
