### ISSUE TITLE
Tool not showing every item in compendium

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#125]
**Feedback Type**: Bug
 
**Core:** 9.280
**System:** dnd5e v1.6.3
**Module Version:** hero-creation-tool v1.8.3
 
**Description**:
Not all of the races and equipment in the compendium are not showing up in the tool. The few items I've noticed:
Hill and Mountain Dwarves
Asaimar
Rock Gnome
Dark Elf (Drow)

I use custom compendiums that I have items imported from D&D Beyond Importer. It does show a majority of the items within the compendium, but not everything. Can't really figure out a common denominator between the items I've noticed since they're from different source books.<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

ATL--v0.4.01;
ActiveAuras--v0.4.13;
JB2A_DnD5e--v0.4.9;
Sequencer-JKASE-Database--v1.0.0;
acelib--v1.8.3;
advanced-macros--vv1.15;
autoanimations--v3.2.991;
bug-reporter--v1.3.3;
chat-portrait--v0.8.0;
color-picker--v0.2;
compendium-browser--v0.8.2;
compendium-folders--v2.4.8;
core-settings-expanded--v1.2.1;
dae--v0.10.32;
ddb-importer--v2.9.67;
dfreds-convenient-effects--v2.7.3;
dice-calculator--v1.5.2;
dice-so-nice--v4.5.1;
dlopen--v1.0;
dnd5e-character-monitor--v1.7.0;
dungeon-draw--v1.0.0;
easy-polls--v1.2.1;
encounter-builder--v0.3.0;
forge-compendium-browser--v1.2.2;
forge-vtt-shared-compendiums-ddb-import--v1.0;
foundry_community_macros--v9.18;
foundry_community_tables--v9.3;
foundryvtt-simple-calendar--v2.0.30;
fvtt-encounter-stats--v0.22.2;
healthEstimate--v28.2;
hero-creation-tool--v1.8.3;
itemacro--v1.8.0;
kctg-common--v0.5.5;
lets-trade-5e--v0.4.2;
lib-wrapper--v1.12.10.0;
link-item-resource-5e--v1.2.2;
lootsheetnpc5e--v3.6.1;
magicitems--v2.2.1;
mcc--v1.3.2;
midi-qol--v0.9.83;
midi-srd--v0.2.03;
miskasmaps--v1.4;
module-credits--v1.1.11;
monks-active-tiles--v1.0.90;
monks-enhanced-journal--v1.0.65;
multi-token-edit--v1.19.0;
npc-chatter--v2.2.0;
party-overview--v2.14.2;
ping-logger--v1.2.20;
polyglot--v1.7.42;
popout--v2.9;
searchanywhere--v2.3.6;
sequencer--v2.2.4;
socketlib--v1.0.10;
stream-view--v0.4.4;
tabletop-rpg-music--v1.7.0;
tidy5e-sheet--v0.5.33;
times-up--v0.8.32;
token-action-hud--v2.3.0;
token-auras--v1.16;
tokenmagic--v0.5.4;
torch--v1.4.4;
trigger-happy--v0.8.39;
turnmarker--v2.9.0;
vtta-tokenizer--v3.9.5;
vueport--v1.1;
forge-vtt--v1.10;
forge-vtt-optional--v1.1;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by Shadowling-McBeard** [comment]
Running into the same issue, also after importing with the D&D Beyond Importer.

However, I'm not sure if everything that's missing is from their compendiums. For example, with Rogue I cannot select Stealth as class proficiency (although it *is* present as an option with Backgrounds).

**Comment by ccjmk** [comment]
I think this is related to the DDBImporter compendia not having parent classes (because for example, Elf is not something you can select, so DDBImporter doesn't create one for that). But the tool needs to to know what features you get from being an Elf, like, Trance.

Solution for this should be selecting both the base SRD compendium  and the DDBImporter compendium for classes, and removing the duplicates. Sorry for the delay, I lost track of this one!

**Comment by ccjmk** [comment]
Closing this one as I sadly can't find a way to reach the original submitter.
