### ISSUE TITLE
Replace Default Starting Gold When Class is Selected

### ISSUE THREAD

**Issue by Dialectikal** [HeroCreationLab/hero-creation-tool#127]
It would be nice if the rollable starting gold was updated with the appropriate value once a class has been selected. Perhaps this should be configurable, since people create custom classes.

In addition, including the following blurb (or something similar) in the explanation in the righthand column would be helpful:

"If you forgo your starting equipment, as well as the items offered by your background, you can roll for an amount of starting gold determined by your chosen class."

**Comment by ccjmk** [comment]
Hi! thanks for the suggestion, it's something I have on the backlog actually, but it requires the Class item to have a way to define the starting gold / gold formula, it's a restriction coming from the system currently.  If you try to make a custom Class on the Items section, you will see that there's no way to define it. 
![image](https://user-images.githubusercontent.com/4467128/211212501-d41be278-1482-4ca7-a1be-4bcc4a7bbae9.png)

once that becomes available, it will be added! :)
