### ISSUE TITLE
It can't show all compendiuns

### ISSUE THREAD

**Issue by brunocalado** [HeroCreationLab/hero-creation-tool#13]
I can scroll to select a compendium. 

![image](https://user-images.githubusercontent.com/4999783/127335862-75a13bb5-a487-47cb-b655-1b95cc3473fb.png)

**Comment by ccjmk** [comment]
can you please try disabling all other modules and trying again ? I think it's probably a css collision with.. something else. I just tried locally expanding all categories and I can get to the bottom without issues:

![image](https://user-images.githubusercontent.com/4467128/127338785-04ac9f45-7d05-40f3-b6dc-ae1da32f1a6a.png)

If that works, depending on the number of modules you have, you can try manually or use https://foundryvtt.com/packages/find-the-culprit/ to ... find the cultrip :P hahah and once we know where the issues is I can fix it. If it does *not* fix with the modules, it's probably browser-related. In which browser are you opening foundry?

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/127340255-74a9ebd8-a69a-4f73-8d8e-a5e1fe3d5fc1.png)

**Comment by ccjmk** [comment]
Ok.. two follow up questions:

1) which browser you using?
2) do you have a humongous amount of compendiums ? I tested this with some +20 compendiums with no issues, but I might have overseen something.

**Comment by brunocalado** [comment]
- win10
- chrome 
- last foundry and dnd

Yes. I have lots of compendiums

**Comment by ccjmk** [comment]
ok, I'll try this later today.. if you open the console (F12) and type 'game.packs' + enter, what number you see next to the Map? I want to try at least your same number

![image](https://user-images.githubusercontent.com/4467128/127355089-994d866d-1872-4c7b-adef-23833e94fbe2.png)

**Comment by brunocalado** [comment]
32
![image](https://user-images.githubusercontent.com/4999783/127357132-5aa6d454-dac2-46bc-8131-bd1dea6e52b4.png)

**Comment by ccjmk** [comment]
Ok, found it! thanks for bringing this up, I will bundle this with the other open issue I have, and fix it on 1.0.1 ! :)

**Comment by brunocalado** [comment]
Thank you for the great work.

**Comment by JawayWu** [comment]
I still have this issue on the latest update with all modules disabled except Hero Creation Tool :(
