### ISSUE TITLE
DNDbeyond importer issues

### ISSUE THREAD

**Issue by LozoTrioxide** [HeroCreationLab/hero-creation-tool#132]
Heya,

The tool is having problems when you want to use the DDB Importer compendiums. 

Some of the races, classes, backgrounds, etc do not show up, and none of the subclasses show up.

Unsure what information to give you so if you need any let me know

**Comment by ccjmk** [comment]
Hi @LozoTrioxide ! Can I ask if you are bringing the compendia with imported stuff from a previous version ? Sadly as the item model has being changing througout the last couple 5e versions, thhehre might be some incompatibilities. But latest 5e version with latest HCT + DDBImporter versions seem to work!

Keep in mind DDB might not be following the module's rules towards races, that are... finicky at best, but it's the best I can do right now based on the SRD foundry provides. Please, be sure that the subrace names have the race name as part of them, like "Sea Elf", something like "Drow" will not work, unless its "Drow Elf"

**Comment by ccjmk** [comment]
@LozoTrioxide another thing to point out is that DDBImporter does *not* create parent races, you need to select both the SRD Races compendium and whatever  compendium  you have from DDBImporter!

**Comment by ccjmk** [comment]
@LozoTrioxide I will need to close this given that I can't find so far any bug on my side, considering the caveat I mentioned. Please, if you are still having issues don't shy away from leaving a message here so I can reopen this.
