### ISSUE TITLE
Auto link Backgrounds to Races (Feature Request, not Issue)

### ISSUE THREAD

**Issue by MythicalRollers** [HeroCreationLab/hero-creation-tool#134]
Not an issue, but a request.  A few races have abilities which are added a specific levels.  Currently, Backgrounds allow for advancement.  I would like to request that any "Backgrounds" in your "Racial Traits/Features" folder show up and are linked to the race by added the Race in the Source field.  This would allow for racial leveled items to auto apply. 
![windcaller](https://user-images.githubusercontent.com/106455111/215510789-ab68910a-b686-4fac-b195-28f54f643ad2.png)

**Comment by ccjmk** [comment]
@MythicalRollers I have good and bad news about this:
Good news is there's definitely going to be a mechanism to add Racial Traits at certain levels, which will use Advancements the same way that it works for Backgrounds and Classes,, so if you are an Aarakocra lv3+ it will be added, in the case of your example.

Sad news is that Races don't currently exist as an Item type; I am waiting for the development on the `dnd5e` system side; once that becomes available, it will be added to the module :) I hope you understand that it doesn't make a lot of sense for me to develop this sort of workaround when it will break as soon as the "real" solution is implemented, as it will build an expectation of how things work by users that will be broken once the real solution is live.
