### ISSUE TITLE
Gold calculation broken/all items have NaNgp for value

### ISSUE THREAD

**Issue by QuillSpirit15971** [HeroCreationLab/hero-creation-tool#137]
When selecting starting equipment, all items selected have a value of "NaNgp", which breaks the calculation for remaining gold. The equipment packs work fine and subtract Gold as normal, but every other item breaks the calculation. Once the calculation breaks the issue persists across heroes, even if the hero it broke for is not finalized. Restarting Foundry resets the calculation, but does not solve the bug.

Default settings for Hero Creation Tool.
No other modules are enabled, and only the SRD compendium is active.

### Initial Equipment page with Gold rolled for Hero "J"
![Goldbug1](https://user-images.githubusercontent.com/126735274/222308186-d3c5e222-5481-4bf6-9eae-df9af74c523d.jpg)

### Pack selected and Gold subtracted for Hero "J"
![Goldbug2](https://user-images.githubusercontent.com/126735274/222308322-a7c8cbc7-0231-47f9-9958-cfae561de01e.jpg)

### Longbow selected and Gold calculation broken for Hero "J"
![Goldbug3](https://user-images.githubusercontent.com/126735274/222308388-1896b08d-b51d-4357-833c-e5902fae9102.jpg)

### Equipment page with persistant calculation break for Hero "K" after rolling Gold
![Goldbug4](https://user-images.githubusercontent.com/126735274/222308478-94e8fef5-f245-47c3-bf89-a4318a8f8808.jpg)

**Comment by ccjmk** [comment]
Oops, yeah this definitely related to the model change from dnd5e <2.x.y to post 2.x.y, I will have most of it fixed already on my end, need to finish some cases and I should be dropping a new version between tomorrow and saturday. Sorry! and thanks for reporting this back to me :)
