### ISSUE TITLE
Hero Tool no longer works

### ISSUE THREAD

**Issue by MythicalRollers** [HeroCreationLab/hero-creation-tool#152]
Foundry: 11.304
dnd5e: 2.2.2
See the two images.
I have shut down all modules except for HCT and my Compendium. 

<img width="541" alt="image" src="https://github.com/HeroCreationLab/hero-creation-tool/assets/106455111/cf4a7b32-0a74-454c-b68b-3776e14b13ec">
<img width="602" alt="image" src="https://github.com/HeroCreationLab/hero-creation-tool/assets/106455111/c4ebf59f-46b5-4758-872a-035b4667a0cb">

**Comment by ccjmk** [comment]
hmmm this looks like a problem on the spells compendium. is it a custom one ? I noticed 2.2.2 was released 2 days ago, so maybe there's some conflict now, I'll check asap!

**Comment by MythicalRollers** [comment]
You are a genius.  I recently bought Crown of the Oathbreaker.  It's spell compendium is what broke things. As soon as I uncheck it, it works.
