### ISSUE TITLE
hello is this project still open

### ISSUE THREAD

**Issue by Zarhog** [HeroCreationLab/hero-creation-tool#162]
Hello there i was wondering if this project is still ongoing. and if so if i would be able to enquire if i could potentialy commision you to do a custome version of it that fixes a lot of its core issues and allows us to utalize it in our server.

**Comment by geoidesic** [comment]
@Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.

**Comment by ChobitsCrazy** [comment]
> @Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.

Is there a bounty? Interested to see if this could be up and going before my next campaign launches.

**Comment by ccjmk** [comment]
I can say I'm at least partially working on having _something_ work, but I'm still far away from anything usable, and I'm not even sure yet if it would make sense to make it work like is has, or just rework the whole thing in a different shape (given how new 5e character sheets have Add Race / Background / Class buttons, it might make sense to make the module guide the user to those options instead)

**Comment by geoidesic** [comment]
> > @Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.
> 
> Is there a bounty? Interested to see if this could be up and going before my next campaign launches.

@ChobitsCrazy There is a bounty: https://discord.com/channels/732325252788387980/1238916345064718388

You can also sponsor me directly here on GitHub: https://github.com/sponsors/geoidesic

@ccjmk (the HCT author) and I have chatted and if enough people sponsor it, I will rebuild this module in a more modern and maintainable codebase and keep it up to date. It will take me two weeks to do, once funded.

Please spread the news.

**Comment by ChobitsCrazy** [comment]
Thanks for your responses! The Discord link doesn't seem to work for me unfortunately.

**Comment by geoidesic** [comment]
I've updated the comment to include the name of the Discord server. Probably you need to join that before the discord link will work.

**Comment by MakatheBaka** [comment]
How much would ya need in sponsorship to have this happen?

**Comment by ccjmk** [comment]
hey @MakatheBaka just FYI there's a post on the commisions channel in the League's discord mentioned above where you can chip in for geoidesic :)

**Comment by geoidesic** [comment]
@MakatheBaka @Zarhog  it has been partly funded. Anything you can add will allow me to take it further. So far about $500 has been donated which is about half of what I requested.

**Comment by geoidesic** [comment]
@MakatheBaka @Zarhog you can also monitor progress by joining the Discord channel I posted above

**Comment by vampiregoat699** [comment]
> @Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.

That would be awesome as I wanted this mod for my game but it will not read races no matter what I try

**Comment by ChobitsCrazy** [comment]
> > @Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.
> 
> That would be awesome as I wanted this mod for my game but it will not read races no matter what I try

Actor studio is now available as a module.

**Comment by Zarhog** [comment]
This can be closed i think :)

**Comment by geoidesic** [comment]
> > @Zarhog you can chat to me about that. I'm not the author of this module but I'm considering picking up where he left off.
> 
> That would be awesome as I wanted this mod for my game but it will not read races no matter what I try

https://foundryvtt.com/packages/foundryvtt-actor-studio

**Comment by geoidesic** [comment]
@ccjmk  perhaps add a link to https://foundryvtt.com/packages/foundryvtt-actor-studio in the readme and archive this repo. Unless you intend to continue with dev on it.
