### ISSUE TITLE
Characters Import at Level 20

### ISSUE THREAD

**Issue by SecretSquirrel77** [HeroCreationLab/hero-creation-tool#19]
When you finish the character creation, the PC is initially created at level 20.

**Comment by ccjmk** [comment]
I don't seem to be able to replicate this; can you reproduce this issue consistently? And if so, are you running any other modules? If possible, use [Find the Cultrip!](https://foundryvtt.com/packages/find-the-culprit/) to pinpoint what module could be causing the issue.

**Comment by SecretSquirrel77** [comment]
This issue is caused by the data in the item details. Class must be set to 1.

**Comment by SecretSquirrel77** [comment]
This issue is caused by the data in the item details. Class must be set to 1.

**Comment by ccjmk** [comment]
you closed the ticket yourself but your explanation was not crystal clear to me, sorry, were you manipulating the data and somehow broke it? hhehe

**Comment by SecretSquirrel77** [comment]
Yep. In details, level must be set to 1. Not 20!
