### ISSUE TITLE
Some items don't open the popup when clicked

### ISSUE THREAD

**Issue by SecretSquirrel77** [HeroCreationLab/hero-creation-tool#22]
![Background](https://user-images.githubusercontent.com/77705375/128517421-53b1602e-aba0-446d-bd2e-58757181e187.PNG)

Backgrounds can be selected, but don't display in the text box. For example, in the screenshot, 'acolyte' is selected, but it does not display in the box to the right.

**Comment by ccjmk** [comment]
oooh I see what you mean. I didn't realise this would be confusing, but its the "standard" behaviour right now: the text box is only shown when you select to create a new feature.

If you select an existing feature, you should be able to click it and see the item pop-up. If I add the text description here, it would then differ from Race/Class features, that also don't show their description.

**Comment by SecretSquirrel77** [comment]
I understand what you mean now. I am not able to open the background item by clicking on it however. Is there something I'm missing?

**Comment by ccjmk** [comment]
Hmm ok, I seemed to have missed something here definitely. From what I could tell on my testing, CREATED items (so, race features or class features, backgrounds, spells) don't pop up the window, some throw an error, some don't. It only works for "default" items, and the ones from DDBImporter also work. So I might be messing up something on my side here, marking this as a bug.

Though rest assured that the items ARE adequately added to the created actor, it's just the visualization that is a little iffy.

**Comment by ccjmk** [comment]
Renaming the issue because I keep coming back to it trying to remember what's wrong in here hahah

**Comment by ccjmk** [comment]
got it! going into next version
