### ISSUE TITLE
Background info to the right.

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#24]
**Feedback Type**: Enhancement
 
**Core:** 0.8.8
**System:** dnd5e v1.4.1
**Module Version:** hero-creation-tool v1.1.0
 
**Description**:
Is it possible to have the background description filled in to the right when a background is selected?<details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by ccjmk** [comment]
I will postpone any big background changes until we have a supporting data type on dnd5e. https://gitlab.com/foundrynet/dnd5e/-/merge_requests/353

But as soon as we have a working type I'll consider this highly.

**Comment by ccjmk** [comment]
Forgot to mark this on the PR but it should show the background description on the side now!
