### ISSUE TITLE
Classes missing 1st level features

### ISSUE THREAD

**Issue by TyphosTheD** [HeroCreationLab/hero-creation-tool#27]
I found a handful of items that seem like are either malfunctioning, or are features that could be cool for additions.

Races:
DAE effects from races/racial features don't carry through
Damage resistance/vulnerabilities/immunities options would be cool
Additional movements options would be helpful
Armor and Weapon proficiencies are each currently titled "tool proficiencies" (I think this was already identified in another issue)
![image](https://user-images.githubusercontent.com/40187548/129902258-a1a0d0df-09df-4098-a8c8-053afa6eb94c.png)

Classes:
Classes don't seem to drag on any level 1 features, nor are there options for proficiencies, saving throws or otherwise
![image](https://user-images.githubusercontent.com/40187548/129902318-f32305ad-d0ee-43b1-9aea-a1ec3414f2c9.png)

Thanks,

**Comment by ccjmk** [comment]
First topic is already identified and corrected, it was just a matter of the translations. About the second topic, I would need to investigate this a little further. Can I contact you through discord one of these days to see it together ?

**Comment by TyphosTheD** [comment]
> First topic is already identified and corrected, it was just a matter of the translations. About the second topic, I would need to investigate this a little further. Can I contact you through discord one of these days to see it together ?

Absolutely. It's should be the same username in Discord.

**Comment by ccjmk** [comment]
Breaking this into multiple issues to keep track of them independently.

**Comment by ccjmk** [comment]
Armor/Weapon proficiencies already taken care on https://github.com/HeroCreationLab/hero-creation-tool/issues/26

**Comment by ccjmk** [comment]
There seemed to be a misalignment of compendia sources - sorted with TyphosTheD, closing this!
