### ISSUE TITLE
Can't select class with " ' " in name.

### ISSUE THREAD

**Issue by Padhiver** [HeroCreationLab/hero-creation-tool#28]
Hello !
First, thank you for this awesome tool, it's perfect for creating heroes when you use custom class or so. I DMing Adventure in Middle Earth in french, and one class have " Frère d'armes" for name, but i can't select this one in the tool (nothing happen) and i have this error :
![image](https://user-images.githubusercontent.com/80126915/130652005-efb22d8c-eaa2-4ccf-9ee0-b4b07d6e4019.png)
So i think it's because of the " ' " but, i dont know if you can do something for that. :)
Thank you !

**Comment by ccjmk** [comment]
I have an idea of what is causing this, I'll be investigating this on the week, sorry for the delay, im a little short on time these days!

**Comment by ccjmk** [comment]
This was indeed an easy fix, I think I got it covered!
