### ISSUE TITLE
Improperly interacting with features that use (DAE) Dynamic Active Effects

### ISSUE THREAD

**Issue by Moremollicon** [HeroCreationLab/hero-creation-tool#29]
Features inside a source compendium for Hero Creation Tool don't seem to function properly if said feature has DAE effects. When an actor is created using the Hero Creation Tool, and features that use DAE are chosen; their effects do not work.

Here is a direct example. I create a feature called fireproof; I add a passive DAE effect that makes it so that the actor in possession of fire proof has resistance to fire damage. I add the feature to an actor. The feature functions as expected with no problems. I add the feature to the source compendium that the Hero Creation Tool uses as its race compendium. I then reference the feature in a race that is in the race compendium. I then create an actor using Hero Creation Tool with a race that references fireproof. Fireproof is added to the actor's features as expected. If I click on the fireproof feature inside the actor's feature tab; the DAE passive effect is still there. However, the automatic resistance to fire damage that should be provided by fireproof does not exist. Instead I will need to delete the fireproof feature, and then manually drag it in from the source compendium to make fireproof function as it should.

I've tested a few other DAE effects, and none of them seem to work if I create an actor that has those features using HCT. Features that are reaction based do not proc when the actor has a chance to make a reaction either. Sound implemented using automated animations appears to function as it should though. 

The DAE effects still appear to be present if I open up the feature and click on the effects page. They simply dont function at all.
Here are my active modules.
![image](https://user-images.githubusercontent.com/89629067/131083738-9a95dfc7-1882-43a7-9e1b-733010f01d61.png)
![image](https://user-images.githubusercontent.com/89629067/131083809-e11d9fc3-71f2-4d73-b60c-c3ab9a1a73cf.png)

Hope the bug gets fixed asap. Cheers mate.

**Comment by ccjmk** [comment]
Sorry for the delay! I'm investigating this now, and I seem to already found the root cause but can't figure out how to fix it just yet, but hopefully this shouldn't take long

**Comment by ccjmk** [comment]
got it!

the item list inside the actor data when calling Actor.create(newActorData) was not transfering the active effects. With help from ghost I split the items aside and created them as embedded documents on the already-created Actor, and it seems to have worked like a charm!
