### ISSUE TITLE
Make the Creator window 'two columns'

### ISSUE THREAD

**Issue by struckyCZ** [HeroCreationLab/hero-creation-tool#37]
Hello,
gotta say this is a pretty awesome module. Have been wishing for something like this for a long time. Although I have a **feature request/enhancement** I'd like to ask for.
Please make the two parts of the window separate as shown on the picture, because when I scroll all the way down on the right part to find something out, like some proficiencies, I loose all the interactive options from the left part and have to scroll all the way up again, and do this again and again.
![image](https://user-images.githubusercontent.com/80347865/131263406-aae3bca9-4e4f-4605-90ff-f087196579fd.png)

Anyways, thank you very much for the module!

**Comment by ccjmk** [comment]
Hi! I actually made it work like that during develop, changed i because the extra scrollbar was a little confusing, but I'll put it under a setting, sure!
