### ISSUE TITLE
Change Dropdown lists to Search Fields

### ISSUE THREAD

**Issue by MaxPat931** [HeroCreationLab/hero-creation-tool#38]
Change the Dropdown lists for Race, Class, and Backgrounds to a Search Field for easier filtering. 
Being able to type in the option you want will help speed up the process of finding selecting your desired feature
eg typing "Half" to display only races with matching text in the list. Although it would be nice to display the whole list by default with no text input, only filtering if you type (unlike the spells and items Search Fields, that only display matching text)

![image](https://user-images.githubusercontent.com/86370342/131735046-dce82d14-2d8f-44ae-96e4-f17b77883aec.png)

**Comment by ccjmk** [comment]
def wanted to do this, i just went for a select because it was an easier solution for a 1st version. I will eventually make this change

**Comment by ccjmk** [comment]
Working on this now, I will make the change for Race and Class for now, I will wait and see how Background items progress on dnd5e core before making any significant change to that tab.

**Comment by ccjmk** [comment]
It doesn't need to be sorted by parent but I do still need to keep an eye of which is the parent race internally, else I wouldn't be able to add the parent's features! 

Also lol yeah thanks for the notice!

**Comment by MaxPat931** [comment]
Oh good point, and I didnt realize that it looks like you're hiding that parent race now too, which I think is a good idea, but it might not be clear to another user that they are necessary, since they wont see them.
