### ISSUE TITLE
Race defaults to racial feature rather than actual race

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#53]
**Submitted By**: Fat Nutt#3787
**Feedback Type**: Bug
 
**Core:** 0.8.9
**System:** dnd5e v1.5.3
**Module Version:** hero-creation-tool v1.3.2
 
**Description**:
I noticed what I believe to be a bug when I was adding custom races from Volo's Guide to Monsters. I was adding the Firbolg race and they have a racial feature called Firbolg Magic. If I linked Firbolg Magic to the Firbolg race I created then the race selector showed Firbolg Magic as the icon / race selector. 

I haven't tried but I feel changing the name from Firbolg Magic to Magic Firbolg or something similar may fix the issue.<details>
<summary>Module Settings</summary>

```js
defaultGoldDice: 5d4 * 10,
showRolls: true,
individualScrolls: false,
enableAbilityScoreRolls: true,
enableAbilityScoreStandardArray: true,
enableAbilityScorePointBuy: true,
enableAbilityScoreManualInput: true,
displayNameMode: 20,
displayBarsMode: 20
```
</details>
<details>
<summary>Active Modules</summary>

breaktime--v1.0.11;
bug-reporter--v1.3.2;
dd-import--v2.2.0;
drag-ruler--v1.8.2;
hero-creation-tool--v1.3.2;
hourglass--v1.0.1;
lazymoney--v0.9.15;
lib-df-hotkeys--v2.3.5;
lib-wrapper--v1.10.8.0;
perfect-vision--v2.10.5;
socketlib--v1.0.9;
token-z--v0.6.1;
torch--v1.4.2;
vtta-tokenizer--v3.4.12;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by FatNutt** [comment]
Hi, I was the bug submitter.
Here's a screenshot of the actual bug. 
![image](https://user-images.githubusercontent.com/76176199/139757662-b478a019-30c4-40da-9214-e34ade9450d4.png)

---
Here's a screenshot of the fix I'm using. I replaced the space in the name with a hyphen.
![image](https://user-images.githubusercontent.com/76176199/139757711-387d9a18-7332-439b-9cb8-8ad409c81bf2.png)

**Comment by ccjmk** [comment]
Hi FatNutt! Thanks for the report, this is actually how the mod behaves naturally, as it takes anything with [Race name] both the name and requirement as a subclass, with some named exceptions. But I will probably refactor that list into a module setting so its customizable for everyone.

But what you did definitely works, just make sure you don't have the word "Firbolg" on a feature name and requirement. Firbolg-Magic without spaces counts as a different word so it works!

**Comment by ccjmk** [comment]
I improved the way races are handled on 1.4.0, this should solve this ticket, as  far as I could test!
