### ISSUE TITLE
Can't see all compendiums 

### ISSUE THREAD

**Issue by JawayWu** [HeroCreationLab/hero-creation-tool#57]
There is a closed issue about this topic, but despite using find the culprit and disabling all modules except for this one, I still can't scroll to see all compendiums.
https://gyazo.com/5be212fc884cd809f8adeb072eba2e3a

**Comment by ccjmk** [comment]
Oops, it seems I somehow broke this again! I will look into it, thanks!

**Comment by ccjmk** [comment]
Can you check just in case if you are in fact seen all compendiums ? I tried on my server where I have the latest version deployed and I noticed the last one looks cut, but its Actually the last one.

![image](https://user-images.githubusercontent.com/4467128/144650656-73e85c18-1a10-4a7e-a4a1-5a33638dcc20.png)

could you try running this on the console: `game.packs.filter(p => p.documentName == "Item").forEach(p => console.log(p.title))` - that should show the names of all the Item packs (and if the last one you see matches the one cut in half in the screenshot, you should be good to go)

Just trying to make sure if this is a fully breaking-bug for someone or its just a visual stuff I can prioritize after V9 migration.

**Comment by JawayWu** [comment]
Hey, I took a second look at it, and you're right, it's just the last one being cut off.
Sorry for the misunderstanding, and good luck with the migration! I can totally deal with a little bit of cut off text haha.

**Comment by ccjmk** [comment]
Np! thanks for reporting it anyway, it _should not_ look like this after all! hahah

**Comment by ccjmk** [comment]
Should be taken care on 1.5.0 release! (just a heads up, 1.5.0 is NOT compatible with foundry 0.8.x, so unless you have a v9 test environment you should not be able to install/update it just yet)
