### ISSUE TITLE
Hero Creation Tool button duplicates.

### ISSUE THREAD

**Issue by Brimcon** [HeroCreationLab/hero-creation-tool#73]
When right clicking the Actors Directory button on the Side Bar the Hero Creation Tool button duplicates.

![image](https://user-images.githubusercontent.com/7198283/147707837-600d2b9f-41a2-42f3-9672-8cc4f66ce711.png)

This is more prominent if you have the side bar collapsed and you click the button to pop it out.
The popped out Directory does not have the Hero Creation tool button.
![image](https://user-images.githubusercontent.com/7198283/147707917-9b1d83cb-f235-4424-a92d-f344aee126ff.png)

This can repeat infinitely.
![image](https://user-images.githubusercontent.com/7198283/147707951-d2442324-abe3-4948-823a-6be1f7f5c390.png)

Using Foundry V.9.238
D&D 1.5.6
Hero Creation Tool 1.5.5

No other Modules enabled.

**Comment by ccjmk** [comment]
Looking into this, thanks for reporting!

**Comment by ccjmk** [comment]
Hi Brimcon! I still haven't had time to really sit and review the code for this, but as an alternative, there's a module setting to put the button for the module inside the Create Actor window, and that would prevent this behavior as a little sideeffect.

![image](https://user-images.githubusercontent.com/4467128/147873639-386d861b-bde0-4cee-af53-65652be71e35.png)

**Comment by ccjmk** [comment]
Got this sorted already, going in with the next version!
