### ISSUE TITLE
Not all races populated from compendium

### ISSUE THREAD

**Issue by rhyst** [HeroCreationLab/hero-creation-tool#74]
Hello,

On a fresh dnd 5e game world it looks like the races are not being populated properly from the compendium:

![image](https://user-images.githubusercontent.com/5313660/148693897-6b40ba0f-bb60-44fe-80bc-515403a10d32.png)

I can select hill dwarf, but not dwarf for example.

Let me know if there's anything else I can proved to debug.

Foundry V.9.242
D&D 1.5.6
Hero Creation Tool 1.5.5
No other modules active

**Comment by ccjmk** [comment]
Hi @rhyst ! What races are you missing ? Remember that the SRD does _**not**_ have all the races from the Player's Handbook, only a single subrace each, and no variant ones. And if memory serves right, those should be all actually: (as a side note, the tool lets you pick only final races, so if a race has subraces (say, Elf), you can't pick it up, only the subraces (continuing with the example of Elf, that would be High Elves only)

In the screenshot I can see:

* Dragonborn
* Dwarf (Hill)
* Elf (High)
* Gnome (Rock)
* Half-Elf
* Halfling (Lightfoot)
* Half-Orc
* Human
* (I see a little bit of extra scroll, I imagine that's the Tiefling)

**Comment by rhyst** [comment]
Ah, I was not familiar with what the SRD is but that makes sense now that I have looked it up. Thank you for your response!
