### ISSUE TITLE
Show ability that governs a skill

### ISSUE THREAD

**Issue by ccjmk** [HeroCreationLab/hero-creation-tool#77]
Waiting for https://gitlab.com/foundrynet/dnd5e/-/merge_requests/470 to be merged before working on this, as it will provide the source of the ability to show.

Expected result e.g. (top instead of bottom)
![image](https://user-images.githubusercontent.com/4467128/149295253-58fd4ad5-afbd-4f3f-b6b0-4877c482f5a0.png)

**Comment by arbron** [comment]
If you wanted to implement this before that MR is merged, you could pull the information directly from the template:

```game.system.template.Actor.templates.creature.skills.acr.ability```

**Comment by ccjmk** [comment]
oh nice! will this be deprecated by the MR eventually ?

**Comment by ccjmk** [comment]
Closed before, somehow the issue remained open.
