### ISSUE TITLE
Button does not appear

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#79]
**Submitted By**: Discord: viktorkrumluisunoss
**Feedback Type**: Bug
 
**Core:** 9.242
**System:** dnd5e v1.5.6
**Module Version:** hero-creation-tool v1.5.6
 
**Description**:
When updating to v9, the button just does not appear in the UI. So I really can't use the module.

I've tried running "Find the culprit" and even only having "Hero Creation Tool" active, but it does not work.<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

about-face--v3.11;
about-time--v1.0.6;
acelib--v1.3.0;
actually-private-rolls--v0.2;
adv-reminder--v0.3;
advanced-macros--v1.13;
advancedspelleffects--v0.8.5.5;
ae-to-chat--v0.3.1;
all-goblins-have-names--v1.3.0;
ammo-tracker-fvtt--v0.2.1;
animated-spell-effects--v0.6.8;
animated-spell-effects-cartoon--v0.1.9;
animated-walls--v0.6;
arbron-context-menus--v0.2.2;
arbron-hp-bar--v2.1.2;
ATL--v0.3.05;
attack-roll-check-5e--v1.2.0;
autoanimations--v1.2.5;
autocomplete-inline-properties--v2.7.1;
babele--v2.2.2;
barbrawl--v1.4.1;
bellows--vv0.4.4;
better-target--v0.1.19;
betterrolls5e--v1.7.1;
betterroofs--v1.3.8;
bug-reporter--v1.3.2;
bullseye-ng--v1.2.0;
CautiousGamemastersPack--v0.6.0;
character-actions-list-5e--v4.3.0;
chat-images--v2.5.6;
chat-notifications--v1.2.3;
chat-portrait--v0.5.35;
chat-scrolling--v0.0.10;
chatreactions--v1.4.0;
clipboard-image--v0.1.3;
colorsettings--v2.8.2;
combat-enhancements--v1.1.0;
combat-numbers--v1.2.1;
combat-utility-belt--v1.8.1;
combatbooster--v2.2;
compact-compendium-list--v0.0.6;
compendium-browser--v0.7.2;
compendium-folders--v2.4.1;
compendium-tools--v0.4.4;
cozy-player--v1.3.1;
cozymaps-free--v1.0.0;
custom-hotbar--v2.2.0;
dae--v0.8.79;
darkness-activated-tiles--v0.2.0;
default-button-visibility-fvtt--v9.242.0;
df-curvy-walls--v3.3.0;
df-qol--v1.7.1;
df-scene-enhance--v3.5.0;
df-settings-clarity--v3.2.1;
dfreds-droppables--v1.4.0;
dfreds-effects-panel--v1.0.0;
dfreds-pocket-change--v3.2.1;
dice-calculator--v1.4.1;
dice-so-nice--v4.3.1;
difficultterrain--v1.0.10;
dnd5e-babele-spanish--v0.4.0;
dnd5e-helpers--v4.0.0;
door-colors--v1.0.2;
drag-all-to-hotbar--v0.0.5;
drag-ruler--v1.10.2;
dragupload--v2.1.0;
dramatic-rolls--v1.5.0;
drawn-wall-generator--v1.1.2;
drop-effects-on-items--v1.0.0;
drop-my-torch--v0.2.1;
Dynamic-Effects-SRD--v6.0.01;
easy-exports--v0.6.2;
easy-target--v2.14;
enhanced-terrain-layer--v1.0.36;
enhancedactiveeffects--v1.1.1;
fateroll--v0.4.6;
find-the-culprit--v1.4.0;
fogmanager--v1.1.1;
food-and-water-tracker--v1.3.1;
forien-copy-environment--v2.0.7;
forien-unidentified-items--v0.4.1;
foundry-filepicker-favorites--v1.1.0;
FoundryVTT-dnd5e-ES--v1.56.1;
foundryvtt-es--v9.242.1;
foundryvtt-show-notes--v0.5;
foundryvtt-simple-calendar--vv1.3.75;
foundryvtt-spell-checker--vv0.1.4-beta;
foundry_community_macros--v9.6;
foundry_community_tables--v9.1;
furnace--v2.6.1;
fvtt-encounter-stats--v0.21.1;
fxmaster--v2.2.2;
game-icons-net--v0.0.18;
game_time_clock--v1.3.2;
gm-notes--v0.5.0;
gm-token-drag-visibility-v2--v2.0.0;
healthEstimate--v26.12;
hero-creation-tool--v1.5.6;
hey-wait--v0.6.3;
hidden-initiative--v1.0.3;
hide-gm-rolls--v0.11.1;
hourglass--v1.1.0;
hue-jass--v0.0.4;
hurry-up--v0.7.2;
illandril-token-hud-scale--v1.4.3;
image-hover--v1.1.8;
initiative-double-click--v1.5;
innocenti-openlock--v0.4.5;
input-expressions--v1.3.4;
inventory-plus--v0.3.5;
item-delete-check--v1.1.6;
item-icon-updater--v0.0.5;
item-piles--v1.2.5;
itemacro--v1.5.6;
itemcollection--v1.8.16;
JB2A_DnD5e--v0.3.4;
journal-icon-numbers--vv1.7.2;
journal-links--v0.3.1;
kandashis-fluid-canvas--v0.3.0;
keybind-lib--v0.3.4;
laptop-fix--v0.0.8;
lessfog--v0.9.0;
lets-trade-5e--v0.4.1;
levels--v2.4.7;
lib-changelogs--v0.7.7;
lib-df-hotkeys--v2.3.5;
lib-wrapper--v1.11.4.0;
libruler--v0.2.0;
LightsHUD--v0.10.4;
link-item-resource-5e--v1.2.1;
lmrtfy--v1.25;
macroeditor--v1.1.2;
magicitems--v2.2.1;
memento-mori--v1.0.1;
merchantsheetnpc--v2.4.2;
metric-ruler-labels--v1.1.0;
midi-qol--v0.8.103;
minimal-ui--v1.4.11;
mob-attack-tool--v0.3.14;
module-credits--v0.0.4.0;
monks-active-tiles--v1.0.49;
monks-enhanced-journal--v1.0.39;
monks-hotbar-expansion--v1.0.12;
monks-little-details--v1.0.43;
monks-scene-navigation--v1.0.21;
monks-tokenbar--v1.0.59;
monks-wall-enhancement--v1.0.6;
more-hooks-5e--v0.4.1;
multilevel-tokens--v1.5.2;
navigation-presets--v1.1.1;
Next-Up--v0.1.14;
nice-more-dice--v1.0.3;
npcgen--v1.1.0;
optional-rules-dnd5e--v0.4.0;
parallaxia--v0.3.6;
party-overview--v2.8.2;
pdf-sheet--v0.11.1;
perfect-vision--v3.5.4;
pick-up-stix--v0.13.8;
pin-cushion--v1.5.0;
pin-fixer--v1.2.1;
ping-logger--v1.2.15;
pings--v1.3.0;
plutonium--v1.46.0;
poi-sheet--v0.1.2;
polyglot--v1.7.28;
popout-resizer--v1.4.2;
potato-or-not--v0.5.0;
query--v0.0.6;
quick-combat--v0.2.8;
quick-module-enable--v1.3.4;
quick-notes--v0.1.1;
quick-status-select--v1.8.0;
quickscale--v1.3.0;
raise-my-hand--v1.1.0;
random-encounters--v0.2.1;
random-everything-generator--v0.1.3;
reset-movement--v1.5.0;
resource-icons--v1.3.0;
resourcesplus--v1.6.12;
rolladvantage-token-stamp-2-foundry--v1.2.1;
rolltable-requester--v1.0.0;
scene-packer--v2.3.27;
sequencer--v2.0.7;
settings-extender--v1.2.0;
sheet-to-token--v0.1;
sidebar-macros--v0.6.0;
sidebar-resizer--v0.4.1;
siftoolkit--v0.4.3;
simplefog--v0.1.18;
smalltime--v1.13.10;
smarttarget--v0.8.5;
smip-compendium--v0.6.0;
socketlib--v1.0.10;
speak-as--v1.2.1;
spell-level-buttons-for-dnd5e--v1.03;
split-journal--v1.1;
statuscounter--v2.0.11;
steves-scenes--v1.0.16;
sticky-rolltable-header--v1.1;
sync-token-name--v1.0.3;
tabbed-chatlog--v1.6.4;
tagger--v1.2.3;
target-recall--v1.1.0;
targetreacts--v2.0.0;
tension-pool--v0058;
terrain-ruler--v1.6.0;
tidy-ui_game-settings--v0.1.30;
tidy5e-sheet--v0.5.21;
times-up--v0.8.31;
token-action-hud--v2.0.13;
token-auras--v1.15;
token-elevator--v1.1.0;
token-frames--v1.2.0;
token-hotbar--v1.3.1;
token-info-icons--v2.3.5;
token-mirror-button--v1.1.0;
token-mold--v2.14.0;
token-owner-selection-tweak--v0.2.0;
token-tooltip-alt--v3.1.2;
tokenmagic--v0.5.3;
travel-pace--v1.1.0;
trigger-happy--v0.8.33;
uchideshi34-lmop-maps--v1.0.0;
update-token-image--v1.0.0;
uses-per-encounter--v1.0.0;
vance-sidebar-resizer--v0.0.2;
variant-encumbrance-dnd5e--v0.7.3;
vtta-tokenizer--v3.5.0;
wall-height--v3.6.0.2;
warpgate--v1.13.2;
weatherblock--v0.7;
WeatherEffects5e--v1.0.0;
WhisperBox--v1.1.1;
window-controls--v1.7.4;
womboras-journal-helper--v0.0.5;
world-explorer--v0.4.0;
zsync--v0.0.4;
_chatcommands--v1.4.0;
_CodeMirror--v5.58.3-fvtt3;
_document-sheet-registrar--v1.0.0;
_introjs--v3.2.1-fvtt4;
_mathjs--v7.5.1-fvtt2;
_sortablejs--v1.14.0-fvtt1;
srd5e--v1.46.0;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by ccjmk** [comment]
Hi! I can't replicate this, but maybe it has to do with a relatively new module setting that allows you to show the button on the Create Actor dialog instead?

![image](https://user-images.githubusercontent.com/4467128/150389052-696eab59-2cd5-4a24-aead-55d2fd21b5f9.png)


![image](https://user-images.githubusercontent.com/4467128/150389150-c7ecfbac-bbe4-42bb-a2dd-a52a776c9038.png)

**Comment by viktorkrumluisunoss** [comment]
Hi ccjmk! Thanks for your answer.

So, I have that feature checked, and I see that window you show me like this:
![image](https://user-images.githubusercontent.com/98216295/150637845-efc587fe-d155-4897-ac9e-3cb23c07f5a2.png)

However, uncheking that option seems to work:
![image](https://user-images.githubusercontent.com/98216295/150637902-509ad091-9283-4ebd-a3e8-c4c26dd76de7.png)

Is there any other way I can help you to find the issue? I usually use an internet browser for foundry.

**Comment by ccjmk** [comment]
Oh, i see! (I actually speak spanish too but leaving this in english in case someone needs to look at this issue in the future).

Ok, got it, I was actually searching for the dialog by name and I had the name in english, forgot to translate that 🤦 I imagine this should be easy to fix; if you see this issue been closed it should mean it's supposed to be fixed! 🎉

**Comment by ccjmk** [comment]
v1.6.1 should fix this! Let me know if you still have any issues, but I tried on Spanish and it worked on my test bench, so hopefully it would be fine!

**Comment by viktorkrumluisunoss** [comment]
It works perfectly now, thanks!
