### ISSUE TITLE
missing "ja.json" file in LANG directory

### ISSUE THREAD

**Issue by pugmalien** [HeroCreationLab/hero-creation-tool#82]
You call for "ja.json" in the "module.json" file, but there's no such file in my latest d/l or update.

I can't code my way out of a wet sack, so I ain't throwing no rocks, just saw the notice in my logging.

**Comment by ccjmk** [comment]
Thanks for the warning! Yes, I actually removed the file intentionally as it's now translated on a separate module: if you want the Japanese localization, you may already have the module from the Japanese community that translates several modules by BrotherSharp. If you are not, and were just reporting the error, you can safely ignore this :) (also, I removed the reference on 1.6.2 so this should no longer happen after that update)
