### ISSUE TITLE
Option to switch between Foot and Meters

### ISSUE THREAD

**Issue by stillday** [HeroCreationLab/hero-creation-tool#87]
It would be useful if you could choose right away whether the character can be created with the Meter or Feats option

**Comment by ccjmk** [comment]
Hi! sorry, I understand enough german to know that german only :P what is a meter in this context?

**Comment by stillday** [comment]
Oh, i am so sorry that i write on german. i mean an option to change from feats to the meter. i play with meters, and when you have the options to switch from feats to meters mag it is easy to create a character and to play with meters

**Comment by ccjmk** [comment]
Gotcha! I'll look into this, thanks for the suggestion!

**Comment by stillday** [comment]
I'd love to, maybe I can send you some code too

**Comment by ccjmk** [comment]
if you want to try and give it a try, by all means go ahead! I'll be happy to review a PR
