### ISSUE TITLE
Problem with the spellcasting class feature

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [HeroCreationLab/hero-creation-tool#94]
**Submitted By**: Discord IAR18#8415
**Feedback Type**: Bug
 
**Core:** 9.249
**System:** dnd5e v1.5.7
**Module Version:** hero-creation-tool v1.7.1
 
**Description**:
When classes are translated to spanish, the hero creation tool does not detect that it is a spellcasting class, even if they give you the spellcasting feature<details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by ccjmk** [comment]
On further investigation, it should actually take the hint from the class item itself, not relying on any Spellcasting/Pact Magic item. i will fix it that way!

**Comment by Darshyne** [comment]
Yes i have the same issue with french translation, anyway this module is very promising :)

**Comment by ccjmk** [comment]
Putting this on hold as there's an open ticket that will impact how this works, and Advancements have already messed up how this could be fixed, so I will wait and fix it once instead of fixing it again later
